version: "3.7"
services:
  connect:
    image: debezium/connect:0.10
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      CONFIG_STORAGE_TOPIC: ${CONNECT_CONFIG_STORAGE_TOPIC}
      OFFSET_STORAGE_TOPIC: ${CONNECT_OFFSET_STORAGE_TOPIC}
    ports:
      - ${CONNECT_PORT}:8083
    depends_on:
      - zookeeper
      - kafka

  kafka:
    image: debezium/kafka:0.10
    environment:
      ZOOKEEPER_CONNECT: zookeeper
      ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
    ports:
      - ${KAFKA_PORT}:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: debezium/zookeeper:0.10
    ports:
      - ${ZOOKEEPER_PORT}:2181

  postgresql:
    image: postgres:11.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_DATA_DIR}:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=${POSTGRES_MAX_WAL_SENDERS}"
      - "-c"
      - "max_replication_slots=${POSTGRES_MAX_REPLICATION_SLOTS}"
    ports:
      - ${POSTGRES_PORT}:5432